#!/bin/bash
. resources/milkOSSystem/printy

function controller__fsCreate() {
  local action=""
  local type=""
  local target=""

  if [ -z "$1" ]; then
    printy @style fg@flatred @continue
    echo "Error: controller__fsCreateRemove >> controller__fsCreate >> controller__fsCreate(): "
    printy @reset
    echo "You must define an action to run on this item."
    exit 1
  fi

  if [ -z "$2" ]; then
    printy @style fg@flatred @continue
    echo "Error: controller__fsCreate >> controller__fsCreate >> controller__fsCreate(): "
    printy @reset
    echo "You must define a type of item to create."
    exit 1
  fi

  if [ -z "$3" ]; then
    printy @style fg@flatred @continue
    echo "Error: controller__fsCreateRemove >> controller__fsCreate >> controller__fsCreate(): "
    printy @reset
    echo "You must define a target for the item you are attempting to create."
    exit 1
  fi

  action=$1
  type=$2
  target=$3

  if [ $action != "create" ]; then 
    echo "Error: controller__fsCreate >> controller__fsCreate >> controller__fsCreate(): "
    echo "You must define an action to actually be create when using controller__fsCreate."
    exit 1
  fi

  

  if [ $type = "file" ]; then
    touch "$target"
    if 

  elif [ $type = "dir" ] ||  [ $type = "directory" ]; then

  fi

}

function controller__fsCreateDelete() {
  local action="" # create | delete
  local type="" # file | dir/directory
  local target="" # path to target item

  if [ -z "$1" ]; then
    printy @style fg@flatred @continue
    echo "Error: controller__fsCreateDelete >> controller__fsCreateDelete(): You must define an action to run on this item."
    printy @reset
    exit 1
  fi

  local action=$1

  if [ $action = "create" ]; then 
    controller__fsCreate "$@"
  elif [ $action = "delete" ]; then
    controller__fsDelete "$@"
  else
    printy @style fg@flatred @continue
    echo "Error: controller__fsCreateDelete >> controller__fsCreateDelete(): "
    printy @reset
    echo "$1 invalid action value passed to controller__fsDelete(). You must specifically use \"create\" or \"delete\""
}