#!/bin/sh

# parrash
# parrash hooks into busybox's shell (ash), in order to force the use of "$@" to correctly parse arguments into new variables.

# attach to ash

env -i ash
. ./parrash


local parameters=""

# when "$@" is called from any ash shell process, override the default output



